networks:
    app-network: # Definisi jaringan custom

services:
    web-main:
        build:
            context: .
            dockerfile: ./apps/web-main/Dockerfile
        container_name: web-main
        hostname: web-main
        restart: always
        ports:
            - "5510:5510"
        networks:
            - app-network # Masukkan container ke dalam network

    react-essentials:
        build:
            context: .
            dockerfile: ./apps/react-essentials/Dockerfile
        container_name: react-essentials
        hostname: react-essentials
        restart: always
        ports:
            - "5511"
        networks:
            - app-network

    tic-tac-toe:
        build:
            context: .
            dockerfile: ./apps/tic-tac-toe/Dockerfile
        container_name: tic-tac-toe
        hostname: tic-tac-toe
        restart: always
        ports:
            - "5512"
        networks:
            - app-network

    investment-calculator:
        build:
            context: .
            dockerfile: ./apps/investment-calculator/Dockerfile
        container_name: investment-calculator
        hostname: investment-calculator
        restart: always
        ports:
            - "5513"
        networks:
            - app-network
