networks:
    app-network: # Definisi jaringan custom

services:
    web-main:
        build:
            context: .
            dockerfile: ./apps/web-main/Dockerfile
        container_name: web-main
        hostname: web-main
        restart: always
        ports:
            - "5510:5510"  # Tetap diekspos ke host
        networks:
            - app-network

    react-essentials:
        build:
            context: .
            dockerfile: ./apps/react-essentials/Dockerfile
        container_name: react-essentials
        hostname: react-essentials
        restart: always
        expose:
            - "80"  # Hanya tersedia dalam network
        networks:
            - app-network

    tic-tac-toe:
        build:
            context: .
            dockerfile: ./apps/tic-tac-toe/Dockerfile
        container_name: tic-tac-toe
        hostname: tic-tac-toe
        restart: always
        expose:
            - "80"  # Hanya tersedia dalam network
        networks:
            - app-network

    investment-calculator:
        build:
            context: .
            dockerfile: ./apps/investment-calculator/Dockerfile
        container_name: investment-calculator
        hostname: investment-calculator
        restart: always
        expose:
            - "80"  # Hanya tersedia dalam network
        networks:
            - app-network
